server:
  port:
    80

spring:
    datasource:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: zzy20040812
      driver-class-name: com.mysql.cj.jdbc.Driver
